### ISSUE TITLE
color in gopher's eyes

### ISSUE THREAD

**Issue by TorchedSammy** [miguelmota/golang-for-nodejs-developers#14]
it looks very scary on dark theme  
![](https://modeus.is-inside.me/V2qMr1M6.png)

**Comment by miguelmota** [comment]
A background color has been applied so gopher appears less scary on dark theme.

![DeepinScreenshot_select-area_20210411105109](https://user-images.githubusercontent.com/168240/114315511-26c27100-9ab4-11eb-8edb-dfaa6ae0745e.png)

Closed by https://github.com/miguelmota/golang-for-nodejs-developers/commit/691e93d767e3e9138c7236fb01913c55c525cce2
