### ISSUE TITLE
Comparison of Node npm and Go dep

### ISSUE THREAD

**Issue by mnoster** [miguelmota/golang-for-nodejs-developers#5]
I think something that would be interesting to add is the comparison of how packages are managed in Node vs Go.

I was thinking an example could be npm vs dep.

**Comment by miguelmota** [comment]
@mnoster yea that'd be good, so such as how to install, upgrade, delete packages, as well how to create and publish packages?

**Comment by mnoster** [comment]
@miguelmota Yeah sure publishing would be cool too.
