### ISSUE TITLE
Promises example

### ISSUE THREAD

**Issue by chebyrash** [miguelmota/golang-for-nodejs-developers#8]
I realise that this is repo is aimed to show how to use *basic* language functionality to achieve similar-to-NodeJS features and we already have an [example](https://github.com/miguelmota/golang-for-nodejs-developers#promises) of using promises in Go.

I wrote a [promise](https://github.com/chebyrash/promise) library for Go inspired by JS promises and their functionality / methods are basically the same.

Do you think it would be a good idea to showcase the library here?

**Comment by chebyrash** [comment]
cc @miguelmota

**Comment by Ramon375** [comment]
Desanclar
